<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\Common\" />
    <Folder Include="Entities\Identities\" />
    <Folder Include="Entities\Domain\" />
    <Folder Include="Entities\Enums\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="DTOs\" />
    <Folder Include="Specifications\" />
  </ItemGroup>

</Project>
