<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GradeManagementSystem.Core\GradeManagementSystem.Core.csproj" />
    <ProjectReference Include="..\GradeManagementSystem.Services\GradeManagementSystem.Services.csproj" />
    <ProjectReference Include="..\GradeManagementSystem.Repository\GradeManagementSystem.Repository.csproj" />
    <ProjectReference Include="..\GradeManagementSystem.Api\GradeManagementSystem.Api.csproj" />
  </ItemGroup>
</Project>
