// <auto-generated />
using System;
using GradeManagementSystem.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradeManagementSystem.Repository.Migrations
{
    [DbContext(typeof(GradeDbContext))]
    partial class GradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcademicYearID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AcademicYearID");

                    b.HasIndex("YearName", "Stage")
                        .IsUnique();

                    b.ToTable("AcademicYears", (string)null);

                    b.HasData(
                        new
                        {
                            AcademicYearID = 1,
                            IsActive = false,
                            Stage = "Junior",
                            YearName = "2022-2023"
                        },
                        new
                        {
                            AcademicYearID = 2,
                            IsActive = false,
                            Stage = "Wheeler",
                            YearName = "2023-2024"
                        },
                        new
                        {
                            AcademicYearID = 3,
                            IsActive = true,
                            Stage = "Senior",
                            YearName = "2024-2025"
                        },
                        new
                        {
                            AcademicYearID = 4,
                            IsActive = true,
                            Stage = "Junior",
                            YearName = "2024-2025"
                        },
                        new
                        {
                            AcademicYearID = 5,
                            IsActive = true,
                            Stage = "Wheeler",
                            YearName = "2024-2025"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AppNotification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("NotificationID");

                    b.HasIndex("TargetRole", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AppNotificationRead", b =>
                {
                    b.Property<int>("NotificationReadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationReadID"));

                    b.Property<int>("NotificationID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("NotificationReadID");

                    b.HasIndex("UserID");

                    b.HasIndex("NotificationID", "UserID")
                        .IsUnique();

                    b.ToTable("NotificationReads", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<int?>("Capacity")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("ClassID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("AcademicYearID", "DepartmentID", "ClassName")
                        .IsUnique();

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 1A",
                            IsActive = true
                        },
                        new
                        {
                            ClassID = 2,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 1B",
                            IsActive = true
                        },
                        new
                        {
                            ClassID = 3,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 2A",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompetencyID"));

                    b.Property<string>("CompetencyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MajorID")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxAttempts")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("CompetencyID");

                    b.HasIndex("MajorID");

                    b.ToTable("Competencies", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.CompetencyAttempt", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptID"));

                    b.Property<int?>("AttemptNumber")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EvaluatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StudentCompetencyStatusID")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("AttemptID");

                    b.HasIndex("EvaluatedBy");

                    b.HasIndex("StudentCompetencyStatusID");

                    b.HasIndex("StudentID");

                    b.ToTable("CompetencyAttempts", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("DepartmentID");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentName = "Mathematics",
                            Description = "Mathematics Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentName = "Science",
                            Description = "Science Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentName = "English",
                            Description = "English Language Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentName = "Social Studies",
                            Description = "Social Studies Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentName = "Physical Education",
                            Description = "Physical Education Department",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.GradeActionLog", b =>
                {
                    b.Property<int>("ActionLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionLogID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorName")
                        .HasColumnType("text");

                    b.Property<int?>("ActorUserID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AfterFinalScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BeforeFinalScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ClassID")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<int?>("TermID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ActionLogID");

                    b.ToTable("GradeActionLogs", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Guardian", b =>
                {
                    b.Property<int>("GuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuardianID"));

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuardianPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GuardianRelation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("GuardianID");

                    b.HasIndex("StudentID");

                    b.ToTable("Guardians", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MajorID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MajorID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("MajorName")
                        .IsUnique();

                    b.ToTable("Majors", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.PreviousSchools", b =>
                {
                    b.Property<int>("PreviousSchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PreviousSchoolID"));

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("PreviousSchoolID");

                    b.HasIndex("StudentID");

                    b.ToTable("PreviousSchools", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.QuarterGradeSubmission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionID"));

                    b.Property<int>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<int>("TermID")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionID");

                    b.HasIndex("StudentID", "SubjectID", "AcademicYearID", "TermID")
                        .IsUnique();

                    b.ToTable("QuarterGradeSubmissions", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.QuarterGradesLock", b =>
                {
                    b.Property<int>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("ClassID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("LockedBy")
                        .HasColumnType("integer");

                    b.HasKey("AcademicYearID", "SubjectID", "DepartmentID", "ClassID");

                    b.ToTable("QuarterGradesLocks", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.ResultApproval", b =>
                {
                    b.Property<int>("ApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalID"));

                    b.Property<int?>("AllResultID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalID");

                    b.HasIndex("AllResultID")
                        .IsUnique();

                    b.ToTable("ResultApprovals", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ClassID")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentAcademicYearID")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EnrollmentDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MajorID")
                        .HasColumnType("integer");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassID");

                    b.HasIndex("CurrentAcademicYearID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("MajorID");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.Property<int>("AllResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllResultID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalSubjectScore")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("GeneratedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("OverallTermStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TermID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalTermScore")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("AllResultID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("StudentID", "SubjectID", "TermID", "AcademicYearID")
                        .IsUnique();

                    b.ToTable("StudentAllResults", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.Property<int>("StudentCompetencyStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentCompetencyStatusID"));

                    b.Property<int?>("CompetencyID")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentAttemptNumber")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxAllowedAttempts")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("StudentCompetencyStatusID");

                    b.HasIndex("CompetencyID");

                    b.HasIndex("StudentID", "CompetencyID")
                        .IsUnique();

                    b.ToTable("StudentCompetencyStatuses", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentPromotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromotionID"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("FromAcademicYearID")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsApproved")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RequestDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int?>("ToAcademicYearID")
                        .HasColumnType("integer");

                    b.HasKey("PromotionID");

                    b.HasIndex("FromAcademicYearID");

                    b.HasIndex("StudentID");

                    b.HasIndex("ToAcademicYearID");

                    b.ToTable("StudentPromotions", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentSubjectTermResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("FinalExamScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Quarter1Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Quarter2Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Quarter3Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Quarter4Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<int?>("TermID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TermTotal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("StudentID", "SubjectID", "TermID", "AcademicYearID")
                        .IsUnique();

                    b.ToTable("StudentSubjectTermResults", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxFinalScore")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxQuarterQ1Score")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxQuarterQ2Score")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxQuarterQ3Score")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxQuarterQ4Score")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxQuarterScore")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SubjectID");

                    b.HasIndex("AcademicYearID");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            SubjectID = 1,
                            AcademicYearID = 3,
                            IsActive = true,
                            MaxFinalScore = 100,
                            MaxQuarterQ1Score = 12,
                            MaxQuarterQ2Score = 13,
                            MaxQuarterQ3Score = 12,
                            MaxQuarterQ4Score = 13,
                            MaxQuarterScore = 25,
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            SubjectID = 2,
                            AcademicYearID = 3,
                            IsActive = true,
                            MaxFinalScore = 100,
                            MaxQuarterQ1Score = 12,
                            MaxQuarterQ2Score = 13,
                            MaxQuarterQ3Score = 12,
                            MaxQuarterQ4Score = 13,
                            MaxQuarterScore = 25,
                            SubjectName = "English"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TeacherID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            EmployeeCode = "TCH001",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Qualifications = "B.Sc. Mathematics"
                        },
                        new
                        {
                            TeacherID = 2,
                            EmployeeCode = "TCH002",
                            HireDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Qualifications = "B.A. English"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.TeacherAssignment", b =>
                {
                    b.Property<int?>("TeacherID")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassID")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AssignedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("TeacherAssignmentID")
                        .HasColumnType("integer");

                    b.HasKey("TeacherID", "ClassID", "SubjectID", "AcademicYearID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeacherAssignments", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TermID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TermID");

                    b.HasIndex("AcademicYearID");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ConcurrencyStamp = "39081a45-da45-4b25-9aca-787bbaf07b22",
                            Description = "System Administrator",
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            ConcurrencyStamp = "6fea2cca-8207-43aa-90dc-006a3755a606",
                            Description = "Student Affairs Officer",
                            Id = 2,
                            Name = "StudentAffairs",
                            NormalizedName = "STUDENTAFFAIRS",
                            RoleName = "Student Affairs"
                        },
                        new
                        {
                            RoleId = 3,
                            ConcurrencyStamp = "7172e6ec-4b75-4da6-8a74-5317a3b4924f",
                            Description = "Teacher Role",
                            Id = 3,
                            Name = "Teacher",
                            NormalizedName = "TEACHER",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 4,
                            ConcurrencyStamp = "0adc8fbb-91cb-4dd7-a957-59453987a14f",
                            Description = "Student Role",
                            Id = 4,
                            Name = "Student",
                            NormalizedName = "STUDENT",
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be729c7f-d1ce-4543-8f75-9a453025a340",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@system.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            FullName = "System Admin",
                            Id = 1,
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SYSTEM.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENYA8Zrd5LoGYV68oOm9/E59pSiucbfv+8+e4I5zx9voIAI5REKOkJ2yoA4NxCUPYg==",
                            PhoneNumberConfirmed = false,
                            RoleId = 1,
                            SecurityStamp = "bc6b0bd0-2e6d-4631-9f37-5cc9540f40d1",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4d6f077-c63e-4dab-8f76-c8beed69f411",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@system.com",
                            EmailConfirmed = true,
                            FirstName = "Student",
                            FullName = "Student Affairs",
                            Id = 2,
                            IsActive = true,
                            LastName = "Affairs",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@SYSTEM.COM",
                            NormalizedUserName = "STAFF",
                            PasswordHash = "AQAAAAIAAYagAAAAEA/hkmvGbeFcTcU81jZWyVAOO+YixBNd9Y/pubiQWCx4FGy9SWa60X1F/fPBQycaEQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "f9d7a40b-130f-432a-8015-3e6381c6f961",
                            TwoFactorEnabled = false,
                            UserName = "staff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AppNotificationRead", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AppNotification", "Notification")
                        .WithMany("Reads")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Classes")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Classes")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Major", "Major")
                        .WithMany("Competencies")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Major");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.CompetencyAttempt", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Teacher", "Evaluator")
                        .WithMany("EvaluatedCompetencies")
                        .HasForeignKey("EvaluatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", "StudentCompetencyStatus")
                        .WithMany("CompetencyAttempts")
                        .HasForeignKey("StudentCompetencyStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("CompetencyAttempts")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evaluator");

                    b.Navigation("Student");

                    b.Navigation("StudentCompetencyStatus");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Guardian", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("Guardians")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Majors")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.PreviousSchools", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("PreviousSchools")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.ResultApproval", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", "StudentAllResults")
                        .WithOne("ResultApproval")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.ResultApproval", "AllResultID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StudentAllResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "CurrentAcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("CurrentAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithOne("Student")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.Student", "UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("CurrentAcademicYear");

                    b.Navigation("Department");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("AllResults")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("AllResults")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("AllResults")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Term", "Term")
                        .WithMany("AllResults")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Competency", "Competency")
                        .WithMany("StudentCompetencyStatuses")
                        .HasForeignKey("CompetencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("StudentCompetencyStatuses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competency");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentPromotion", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "FromAcademicYear")
                        .WithMany("PromotionsFrom")
                        .HasForeignKey("FromAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("PromotionsFrom")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "ToAcademicYear")
                        .WithMany("PromotionsTo")
                        .HasForeignKey("ToAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromAcademicYear");

                    b.Navigation("Student");

                    b.Navigation("ToAcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentSubjectTermResult", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Term", "Term")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithOne("Teacher")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.Teacher", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.TeacherAssignment", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Class", "Class")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Teacher", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Terms")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AcademicYear", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("Classes");

                    b.Navigation("PromotionsFrom");

                    b.Navigation("PromotionsTo");

                    b.Navigation("Students");

                    b.Navigation("SubjectTermResults");

                    b.Navigation("Subjects");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AppNotification", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.Navigation("StudentCompetencyStatuses");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Department", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Majors");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.Navigation("Competencies");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("CompetencyAttempts");

                    b.Navigation("Guardians");

                    b.Navigation("PreviousSchools");

                    b.Navigation("PromotionsFrom");

                    b.Navigation("StudentCompetencyStatuses");

                    b.Navigation("SubjectTermResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.Navigation("ResultApproval");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.Navigation("CompetencyAttempts");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("SubjectTermResults");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.Navigation("EvaluatedCompetencies");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("SubjectTermResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizID"));

                    b.Property<int>("AcademicYearID")
                        .HasColumnType("integer");

                    b.Property<int>("ClassID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByTeacherID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("QuizDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("QuizID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("ClassID");

                    b.HasIndex("CreatedByTeacherID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.QuizGrade", b =>
                {
                    b.Property<int>("QuizGradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizGradeID"));

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("QuizID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("QuizGradeID");

                    b.HasIndex("StudentID");

                    b.HasIndex("QuizID", "StudentID")
                        .IsUnique();

                    b.ToTable("QuizGrades", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
