// <auto-generated />
using System;
using GradeManagementSystem.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeManagementSystem.Repository.Migrations
{
    [DbContext(typeof(GradeDbContext))]
    partial class GradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AcademicYearID");

                    b.ToTable("AcademicYears", (string)null);

                    b.HasData(
                        new
                        {
                            AcademicYearID = 1,
                            IsActive = false,
                            Stage = "Junior",
                            YearName = "2022-2023"
                        },
                        new
                        {
                            AcademicYearID = 2,
                            IsActive = false,
                            Stage = "Wheeler",
                            YearName = "2023-2024"
                        },
                        new
                        {
                            AcademicYearID = 3,
                            IsActive = true,
                            Stage = "Senior",
                            YearName = "2024-2025"
                        },
                        new
                        {
                            AcademicYearID = 4,
                            IsActive = true,
                            Stage = "Junior",
                            YearName = "2024-2025"
                        },
                        new
                        {
                            AcademicYearID = 5,
                            IsActive = true,
                            Stage = "Wheeler",
                            YearName = "2024-2025"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ClassID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.HasIndex("DepartmentID");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 1A",
                            IsActive = true
                        },
                        new
                        {
                            ClassID = 2,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 1B",
                            IsActive = true
                        },
                        new
                        {
                            ClassID = 3,
                            AcademicYearID = 3,
                            Capacity = 30,
                            ClassName = "Class 2A",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyID"));

                    b.Property<string>("CompetencyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MajorID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxAttempts")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CompetencyID");

                    b.HasIndex("MajorID");

                    b.ToTable("Competencies", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.CompetencyAttempt", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptID"));

                    b.Property<int?>("AttemptNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EvaluatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentCompetencyStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("AttemptID");

                    b.HasIndex("EvaluatedBy");

                    b.HasIndex("StudentCompetencyStatusID");

                    b.HasIndex("StudentID");

                    b.ToTable("CompetencyAttempts", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DepartmentID");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Mathematics",
                            Description = "Mathematics Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Science",
                            Description = "Science Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "English",
                            Description = "English Language Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Social Studies",
                            Description = "Social Studies Department",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentID = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Physical Education",
                            Description = "Physical Education Department",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Guardian", b =>
                {
                    b.Property<int>("GuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardianID"));

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GuardianPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GuardianRelation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("GuardianID");

                    b.HasIndex("StudentID");

                    b.ToTable("Guardians", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MajorID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("MajorName")
                        .IsUnique();

                    b.ToTable("Majors", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.PreviousSchools", b =>
                {
                    b.Property<int>("PreviousSchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreviousSchoolID"));

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("PreviousSchoolID");

                    b.HasIndex("StudentID");

                    b.ToTable("PreviousSchools", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.ResultApproval", b =>
                {
                    b.Property<int>("ApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalID"));

                    b.Property<int?>("AllResultID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalID");

                    b.HasIndex("AllResultID")
                        .IsUnique()
                        .HasFilter("[AllResultID] IS NOT NULL");

                    b.ToTable("ResultApprovals", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int?>("ClassID")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentAcademicYearID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnrollmentDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MajorID")
                        .HasColumnType("int");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassID");

                    b.HasIndex("CurrentAcademicYearID");

                    b.HasIndex("MajorID");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.Property<int>("AllResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllResultID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalSubjectScore")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("GeneratedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("OverallTermStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TermID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalTermScore")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("AllResultID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("StudentID", "SubjectID", "TermID", "AcademicYearID")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL AND [SubjectID] IS NOT NULL AND [TermID] IS NOT NULL AND [AcademicYearID] IS NOT NULL");

                    b.ToTable("StudentAllResults", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.Property<int>("StudentCompetencyStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentCompetencyStatusID"));

                    b.Property<int?>("CompetencyID")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentAttemptNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxAllowedAttempts")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("StudentCompetencyStatusID");

                    b.HasIndex("CompetencyID");

                    b.HasIndex("StudentID", "CompetencyID")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL AND [CompetencyID] IS NOT NULL");

                    b.ToTable("StudentCompetencyStatuses", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentPromotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionID"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int?>("FromAcademicYearID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsApproved")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RequestDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("ToAcademicYearID")
                        .HasColumnType("int");

                    b.HasKey("PromotionID");

                    b.HasIndex("FromAcademicYearID");

                    b.HasIndex("StudentID");

                    b.HasIndex("ToAcademicYearID");

                    b.ToTable("StudentPromotions", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentSubjectTermResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("FinalExamScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Quarter1Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Quarter2Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int?>("TermID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TermTotal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("StudentID", "SubjectID", "TermID", "AcademicYearID")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL AND [SubjectID] IS NOT NULL AND [TermID] IS NOT NULL AND [AcademicYearID] IS NOT NULL");

                    b.ToTable("StudentSubjectTermResults", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxFinalScore")
                        .HasColumnType("int");

                    b.Property<int?>("MaxQuarterScore")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectID");

                    b.HasIndex("AcademicYearID");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            SubjectID = 1,
                            AcademicYearID = 3,
                            IsActive = true,
                            MaxFinalScore = 100,
                            MaxQuarterScore = 25,
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            SubjectID = 2,
                            AcademicYearID = 3,
                            IsActive = true,
                            MaxFinalScore = 100,
                            MaxQuarterScore = 25,
                            SubjectName = "English"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            EmployeeCode = "TCH001",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Qualifications = "B.Sc. Mathematics"
                        },
                        new
                        {
                            TeacherID = 2,
                            EmployeeCode = "TCH002",
                            HireDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Qualifications = "B.A. English"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.TeacherAssignment", b =>
                {
                    b.Property<int?>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int?>("ClassID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TeacherAssignmentID")
                        .HasColumnType("int");

                    b.HasKey("TeacherID", "ClassID", "SubjectID", "AcademicYearID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeacherAssignments", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermID"));

                    b.Property<int?>("AcademicYearID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TermID");

                    b.HasIndex("AcademicYearID");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ConcurrencyStamp = "fa88e41f-77bd-40aa-ad0e-fe9eb2d7f890",
                            Description = "System Administrator",
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            ConcurrencyStamp = "1c17be33-4e53-4a49-8d3a-05725a402159",
                            Description = "Student Affairs Officer",
                            Id = 2,
                            Name = "StudentAffairs",
                            NormalizedName = "STUDENTAFFAIRS",
                            RoleName = "Student Affairs"
                        },
                        new
                        {
                            RoleId = 3,
                            ConcurrencyStamp = "20d23627-4f65-4c0b-b484-6babe64987b6",
                            Description = "Teacher Role",
                            Id = 3,
                            Name = "Teacher",
                            NormalizedName = "TEACHER",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 4,
                            ConcurrencyStamp = "c009c2ca-725a-4f3f-9711-72fd24ef2e7d",
                            Description = "Student Role",
                            Id = 4,
                            Name = "Student",
                            NormalizedName = "STUDENT",
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "56fe0c8d-3c64-41d4-a3e2-fa9be9d2c7f6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@system.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            FullName = "System Admin",
                            Id = 1,
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SYSTEM.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBbvv0HAlCPksr7pu1kf3fK7Xli+hmPUnVyz9ypkWnm5+nipw4QDrJusJUX3vle+xw==",
                            PhoneNumberConfirmed = false,
                            RoleId = 1,
                            SecurityStamp = "0a4507c4-d2e0-4b4b-83f0-47ef1e170bda",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfc9dac9-fa60-4125-a36a-89ffe2930c2d",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@system.com",
                            EmailConfirmed = true,
                            FirstName = "Student",
                            FullName = "Student Affairs",
                            Id = 2,
                            IsActive = true,
                            LastName = "Affairs",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@SYSTEM.COM",
                            NormalizedUserName = "STAFF",
                            PasswordHash = "AQAAAAIAAYagAAAAEJocIv0CXiClG0cEeXV4UOEJ9qjzCxxOMVOj9oXMNL4DY2rjdOhq77djdzk+hRDgyw==",
                            PhoneNumberConfirmed = false,
                            RoleId = 2,
                            SecurityStamp = "0a8e383a-6438-4275-a6ff-9bbd959353bc",
                            TwoFactorEnabled = false,
                            UserName = "staff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Classes")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Classes")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Major", "Major")
                        .WithMany("Competencies")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Major");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.CompetencyAttempt", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Teacher", "Evaluator")
                        .WithMany("EvaluatedCompetencies")
                        .HasForeignKey("EvaluatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", "StudentCompetencyStatus")
                        .WithMany("CompetencyAttempts")
                        .HasForeignKey("StudentCompetencyStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("CompetencyAttempts")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evaluator");

                    b.Navigation("Student");

                    b.Navigation("StudentCompetencyStatus");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Guardian", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("Guardians")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Majors")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.PreviousSchools", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("PreviousSchools")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.ResultApproval", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", "StudentAllResults")
                        .WithOne("ResultApproval")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.ResultApproval", "AllResultID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StudentAllResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "CurrentAcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("CurrentAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithOne("Student")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.Student", "UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("CurrentAcademicYear");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("AllResults")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("AllResults")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("AllResults")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Term", "Term")
                        .WithMany("AllResults")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Competency", "Competency")
                        .WithMany("StudentCompetencyStatuses")
                        .HasForeignKey("CompetencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("StudentCompetencyStatuses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competency");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentPromotion", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "FromAcademicYear")
                        .WithMany("PromotionsFrom")
                        .HasForeignKey("FromAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("PromotionsFrom")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "ToAcademicYear")
                        .WithMany("PromotionsTo")
                        .HasForeignKey("ToAcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromAcademicYear");

                    b.Navigation("Student");

                    b.Navigation("ToAcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentSubjectTermResult", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Student", "Student")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Term", "Term")
                        .WithMany("SubjectTermResults")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithOne("Teacher")
                        .HasForeignKey("GradeManagementSystem.Core.Entities.Domain.Teacher", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.TeacherAssignment", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Class", "Class")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Subject", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.Teacher", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Domain.AcademicYear", "AcademicYear")
                        .WithMany("Terms")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.AcademicYear", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("Classes");

                    b.Navigation("PromotionsFrom");

                    b.Navigation("PromotionsTo");

                    b.Navigation("Students");

                    b.Navigation("SubjectTermResults");

                    b.Navigation("Subjects");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Competency", b =>
                {
                    b.Navigation("StudentCompetencyStatuses");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Department", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Majors");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Major", b =>
                {
                    b.Navigation("Competencies");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Student", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("CompetencyAttempts");

                    b.Navigation("Guardians");

                    b.Navigation("PreviousSchools");

                    b.Navigation("PromotionsFrom");

                    b.Navigation("StudentCompetencyStatuses");

                    b.Navigation("SubjectTermResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentAllResults", b =>
                {
                    b.Navigation("ResultApproval");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.StudentCompetencyStatus", b =>
                {
                    b.Navigation("CompetencyAttempts");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Subject", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("SubjectTermResults");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Teacher", b =>
                {
                    b.Navigation("EvaluatedCompetencies");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Domain.Term", b =>
                {
                    b.Navigation("AllResults");

                    b.Navigation("SubjectTermResults");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GradeManagementSystem.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
