<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  
  <PropertyGroup>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
</PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Specifications\" />
  </ItemGroup>

</Project>
